### ISSUE TITLE
When things are playing, this module just decides that there is nothing playing.

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-OnSpotify#11]

**Comment by Fabrizz** [comment]
Can you check the console to see any problems? Depending on which device are you using the Spotify API reports a "transition" state, were it is playing, but whats playing is not in the response. There I needed to decide between the module retaining the last media item or changing state.Still, it almost never an issue, since its just a momentary thing. If you manage to catch anything in the web console or the backend console please send it here
