### ISSUE TITLE
After install update, MM language changes to US

### ISSUE THREAD

**Issue by htilburgs** [Fabrizz/MMM-OnSpotify#32]
Normaly my MM language is Dutch, but after installing this update the language changes to US (English).
Whatever I try, I can't get my dutch language (NL) back working until I disable MMM-OnSpotify module.

Second problem is that my Calendar module becomes black/white, where befory the Icons where RED.
Disable MMM-OnSpotify returns to original view

**Comment by Fabrizz** [comment]
Hi, the language this is strange, It should not change your MM2 config, and if there is a problem in a translation file or its not found, MM2 just ignores it. If you can seen here the logs for MM2 or the frontend maybe I could see if there is a problem.

Regarding the color, Im going to change a setting in a coming update so it does not collide with custom CSS, its because it prepares for theming other modules. You can comment the ICONS line in `custom.css`

**Comment by Fabrizz** [comment]
[Its now fixed in V3.1.0](https://github.com/Fabrizz/MMM-OnSpotify/releases/tag/v3.1.0), both the icon color change (now the helper css classes are loaded on a separated file), and the clock translation error (locale settings were getting overwritten by the module instance of the `moment` library). Thanks

**Comment by htilburgs** [comment]
I’m now in Germany, but Will install tomorrow and let you know

**Comment by htilburgs** [comment]
Problem solved!

**Comment by Fabrizz** [comment]
> Problem solved!

Thanks!
